### ISSUE TITLE
base16-builder

### ISSUE THREAD

**Issue by idleberg** [PrismJS/prism-themes#1]
I just wanted to mention that Chris Kempson's [base16-builder](https://github.com/chriskempson/base16-builder) has support for Prism. If this repository is ready to go, I themes built with it.

**Comment by LeaVerou** [comment]
Um, sorry for the n00b question, but what exactly is it? I visited the link above and couldn't tell…

**Comment by idleberg** [comment]
Oh, it's a basically a script that builds themes for a variety of applications. Up to 16 colours can be defined in a YML file (”schemes”) and the themes will be built from the application templates. Supported are a plethora of text editors and CLIs, but also a variety of syntax highlighters — including Prism.

**Comment by atelierbram** [comment]
@LeaVerou You can see examples of themes build with Base16 [over here as part of this repo I made](http://atelierbram.github.io/syntax-highlighting/prism/), which needs updating btw. Am curious to see how the setup for this would be, for example will there be a place for Preprocessors? If so, then Base16 can help out too in generating those files from colorschemes. I made two [example erb files in a Gist](https://gist.github.com/atelierbram/4f7954aa660fc059f488) of these: a light and a dark variation for Sass. (_Obviously with a set template like this, only the colors are variable, so a colorscheme like "Coy"  for example would require something else_). I think this could be helpfull, in a practical sense, but also because it encourages more unity within a design.
@idleberg Also curious about your ideas on this. To clarify, one could have a fork of Base16-builder in a stripped down version for this over here as well.

**Comment by Golmote** [comment]
@atelierbram I just added the first few themes. Two of them were heavily based on ones from your repo.

**Comment by atelierbram** [comment]
@Golmote Cool, thanks for this. Later this weekend I can do I pull request for the base16-themes. Not all of them though; some of them only work with either the light - or the dark version.

**Comment by Golmote** [comment]
Sure. @LeaVerou will then decide whether she wants to include each one of them.

**Comment by chibicode** [comment]
For those looking for more themes than base16, @atelierbram ported DuoTone themes (originally made for Atom) to Prism as well. Thank you!
https://github.com/atelierbram/syntax-highlighting/

**Comment by LeaVerou** [comment]
Nice!

**Comment by atelierbram** [comment]
@chibicode thanks for the heads up! It made me think I should no longer wait doing a PR over here.

Anyway, I basically started all over with converting [DuoTone Themes for Atom](http://simurai.com/projects/2016/01/01/duotone-themes) with a better thought out approach. Now based on [a fork of Base16-Builder](https://github.com/base16-builder/base16-builder) and renamed the project to [Base2Tone](http://base2t.one/); still early days, but the humble beginnings are there, and this enables generating both dark - and light themes from one colorscheme (32 values).

One thing I noticed in relation to CSS highlighting is that Duotone really needs the "number tag" which will be there when checking the option "CSS Extras" when generating a javaScript file from [Prism's download page](http://prismjs.com/download.html).

**Comment by mAAdhaTTah** [comment]
I believe these have generally been added and are good to go, so going to close this as resolved. Happy to take PRs related to this going forward if anything has been missed.
